### ISSUE TITLE
GlycineMine: Gene pages BLAST button 

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/mine-issues#180]
I was working on GlycineMine when I noticed an issue I wanted to submit so that it was documented.

On the GlycineMine gene page there is a "BLAST" button to the right of the gene ID. See screen shot:
![Screenshot 2024-12-18 at 19 00 07](https://github.com/user-attachments/assets/a65711ac-238c-43dc-b11d-d086dc9cc7d4)

This button leads to the [legumeinfo sequence server](https://mines.legumeinfo.org/sequenceserver/) which does not contain the latest Glycine genomes. 

Please change the URL for the button so that users are directed to the SoyBase sequence server which has the most recent Glycine genomes. 
https://www.soybase.org/tools/sequenceserver/

**Comment by adf-ncgr** [comment]
@jd-campbell I thought this would be an easy one, and it was on the intermine end but currently the intended functionality (of posting sequences from the mine to the BLAST) doesn't work because of CSRF protection stuff that got added to SequenceServer in one of the releases- @nathanweeks had pointed this out a while back and I hacked a fix into the legumeinfo sequenceserver, but it looks like perhaps they recently got something into the main codebase that addresses the same issue: https://github.com/wurmlab/sequenceserver/pull/810
@nathanweeks are you managing the soybase sequenceserver? If so, let me know how you want to proceed with getting a fix in for that; in the meantime I will revert the change I made to retarget the blast button until the soybase one is functional (some blast targets are better than no blast at all!)

**Comment by adf-ncgr** [comment]
@nathanweeks the tweaks I mentioned are in this commit: https://github.com/legumeinfo/sequenceserver/commit/b5fa1318e10edf0b30cd76ae251ad700c3796c04
but there's some other stuff mixed up with the relevant ones. Probably will be obvious but the relevant changes are the ones to lib/sequenceserver/routes.rb and public/js/form.js Not sure how this compares to what was done in that PR, although it looks like they didn't touch the form, probably because they're looking at it from a pure API point of view.

**Comment by nathanweeks** [comment]
@adf-ncgr Thanks for the helpful links. Should be fixed now.

**Comment by adf-ncgr** [comment]
Hmm, I still get `405 Not Allowed` when I try to post to https://www.soybase.org/tools/sequenceserver/
either I have misconstrued what the issue is or something went amiss with the tweaking. Let me know if there's anything informative in the logs if you can.

**Comment by adf-ncgr** [comment]
Either you just changed something or I was hallucinating, seems to be working now from the dev glycinemine.

**Comment by adf-ncgr** [comment]
Oh, I see what I did; in the prod context I had specified https://www.soybase.org/tools/sequenceserver/ which should have been https://soybase.sequenceserver.org ; I got it right in the dev context (works on my machine!) 
all's well that ends well; closing.
